accounts/passwords/urls.py
# accounts.passwords.urls.py 
from django.urls import path, re_path
from django.contrib.auth import views as auth_views

urlpatterns  = [
       path('password/change/', 
                auth_views.PasswordChangeView.as_view(), 
                name='password_change'),
       path('password/change/done/',
                auth_views.PasswordChangeDoneView.as_view(), 
                name='password_change_done'),
       path('password/reset/', 
                auth_views.PasswordResetView.as_view(), 
                name='password_reset'),
       path('password/reset/done/', 
                auth_views.PasswordResetDoneView.as_view(), 
                name='password_reset_done'),
       re_path('password/reset/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/', 
                auth_views.PasswordResetConfirmView.as_view(), 
                name='password_reset_confirm'),
       path('password/reset/complete/', 
                auth_views.PasswordResetCompleteView.as_view(), 
                name='password_reset_complete'),
]

accounts/urls.py
from django.urls import path, re_path

from .views import (
        AccountHomeView, 
        AccountEmailActivateView,
        UserDetailUpdateView,
        )
app_name = 'account'
urlpatterns = [
    path('', AccountHomeView.as_view(), name='home'),
    #re_path(r'^(?P<short_name>[\w.@+-]+)/$', AccountHomeView.as_view(), name='home'), to use the username or short name in the url convention
#     path('userdetail/', UserDetailUpdateView.as_view(), name='user-update'),
    path('userdetail/', UserDetailUpdateView, name='user-update'),
    re_path(r'^email/confirm/(?P<key>[0-9A-Za-z]+)/$', 
            AccountEmailActivateView.as_view(), 
            name='email-activate'),
    path('email/resend-activation/', 
            AccountEmailActivateView.as_view(), 
            name='resend-activation'),
]

dating/urls.py
from django.conf import settings
from django.conf.urls.static import static

from django.contrib import admin
from django.urls import path, re_path, include

#ACCOUNT VIEW IMPORTS
from django.contrib.auth.views import LogoutView
from django.views.generic import TemplateView, RedirectView
from accounts.views import LoginView, RegisterView#, StaffRegisterView

#Project Main Views (home, about, contact)
from .views import index

# from questions.views import single, home
# from newsletter.views import contact
# from likes.views import like_user
# from profiles.views import profile_edit, profile_user, profile_view, job_add, jobs_edit

urlpatterns = [
    path('admin/', admin.site.urls),

    # Home, Contact & About urls
    path('', index, name='home'),

    #ACCOUNT LINKS AND PASSWORD(LOGIN & LOGOUT)
    path('accounts/', RedirectView.as_view(url='/account')),
    path('account/', include("accounts.urls", namespace='account')),
    path('accounts/', include("accounts.passwords.urls")),
    path('login/', LoginView.as_view(), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('register/', RegisterView.as_view(), name='register'),

    #APPS URLS
    # path('', 'dashboard.views.home', name='home'),
    # re_path(r'^question/(?P<id>\d+)/$', single, name='question_single'),
    # path('question/', home, name='question_home'),
    # path('contact/', contact, name='contact'),
    # path('matches/', include('matches.urls', namespace='matches')),
    # re_path(r'^like/(?P<id>\d+)/$', like_user, name='like_user'),
    # path('profile/edit/', profile_edit, name='profile_edit'),
    # re_path(r'^profile/(?P<username>[\w.@+-]+)/$', profile_view, name='profile'),
    # path('profile/jobs/add/', job_add, name='job_add'),
    # path('profile/jobs/edit/', jobs_edit, name='jobs_edit'),
    # path('profile/', profile_user, name='profile_user'),
]

if settings.DEBUG:
    urlpatterns = urlpatterns + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns = urlpatterns + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

accounts/forms.py
from django import forms
from django.contrib.auth import authenticate, login, get_user_model
from django.contrib.auth.forms import ReadOnlyPasswordHashField
from django.urls import reverse
from django.utils.safestring import mark_safe

User = get_user_model()

from .models import EmailActivation, Profile
from phonenumber_field.modelfields import PhoneNumberField
from localflavor.us.forms import USSocialSecurityNumberField, USStateField, USZipCodeField 
from localflavor.us.us_states import STATE_CHOICES
from django_countries.widgets import CountrySelectWidget


# write forms below
class ReactivateEmailForm(forms.Form):
    email       = forms.EmailField()

    def clean_email(self):
        email = self.cleaned_data.get('email')
        qs = EmailActivation.objects.email_exists(email) 
        if not qs.exists():
            register_link = reverse("register")
            msg = """This email does not exists, would you like to <a href="{link}">register</a>?
            """.format(link=register_link)
            raise forms.ValidationError(mark_safe(msg))
        return email

class UserAdminCreationForm(forms.ModelForm):
    """A form for creating new users. Includes all the required
    fields, plus a repeated password."""
    password1 = forms.CharField(label='Password', widget=forms.PasswordInput)
    password2 = forms.CharField(label='Password confirmation', widget=forms.PasswordInput)

    class Meta:
        model = User
        fields = ('first_name', 'middle_name', 'surname', 'email') #'full_name',)

    def clean_password2(self):
        # Check that the two password entries match
        password1 = self.cleaned_data.get("password1")
        password2 = self.cleaned_data.get("password2")
        if password1 and password2 and password1 != password2:
            raise forms.ValidationError("Passwords don't match")
        return password2

    def save(self, commit=True):
        # Save the provided password in hashed format
        user = super(UserAdminCreationForm, self).save(commit=False)
        user.set_password(self.cleaned_data["password1"])
        if commit:
            user.save()
        return user

class UserAdminChangeForm(forms.ModelForm):
    """A form for updating users. Includes all the fields on
    the user, but replaces the password field with admin's
    password hash display field.
    """
    password = ReadOnlyPasswordHashField() #can be chnaged to view passwords online in the admin

    class Meta:
        model = User
        fields = ('first_name', 'middle_name', 'surname', 'password', 'is_active', 'is_staff', 'is_client', 'is_superuser')

    def clean_password(self):
        # Regardless of what the user provides, return the initial value.
        # This is done here, rather than on the field, because the
        # field does not have access to the initial value
        return self.initial["password"]

class UserDetailChangeForm(forms.ModelForm):
    # company_name = forms.CharField(label='Name', required=False, widget=forms.TextInput(attrs={"class": 'form-control'}))

    class Meta:
        model = User
        fields = ('first_name', 'middle_name', 'surname')

class UserRegisterForm(forms.ModelForm):
    """A form for creating new users. Includes all the required
    fields, plus a repeated password."""
    password1 = forms.CharField(label='Password', widget=forms.PasswordInput)
    password2 = forms.CharField(label='Password confirmation', widget=forms.PasswordInput)

    class Meta:
        model = User
        fields = ('first_name', 'middle_name', 'surname', 'email') #'full_name',)

    def clean_password2(self):
        # Check that the two password entries match
        password1 = self.cleaned_data.get("password1")
        password2 = self.cleaned_data.get("password2")
        if password1 and password2 and password1 != password2:
            raise forms.ValidationError("Passwords don't match")
        return password2

    def save(self, commit=True):
        # Save the provided password in hashed format
        user = super(UserRegisterForm, self).save(commit=False)
        user.set_password(self.cleaned_data["password1"])
        user.is_active = False # send confirmation email via signals
        user.is_client = True
        # obj = EmailActivation.objects.create(user=user)
        # obj.send_activation_email()
        if commit:
            user.save()
        return user

class ProfileEditForm(forms.ModelForm):
    SEX = (
        ('s', 'SEX'),
        ('m', 'MALE'),
        ('f', 'FEMALE'),
    )
    MARITAL = (
        ('si', 'SINGLE'),
        ('ma', 'MARRIED'),
        ('di', 'DIVORCED'),
        ('se', 'SEPERATED'),
    )
    KIDS = (
        ('no', 'NO'),
        ('yes', 'YES'),
        ('maybe', 'MAYBE')
    )
    SEX_INTEREST = (
        ('m', 'MALE'),
        ('f', 'FEMALE'),
        ('b', 'MALE & FEMALE'),
    )
    PROFILE_STATE_CHOICES = list(STATE_CHOICES)
    PROFILE_STATE_CHOICES.insert(0, ('', 'STATES'))
    sex = forms.CharField(widget=forms.Select(choices=SEX))
    marital = forms.CharField(widget=forms.Select(choices=MARITAL))
    kids = forms.CharField(widget=forms.Select(choices=KIDS))
    interest = forms.CharField(widget=forms.Select(choices=SEX_INTEREST))
    DOB = forms.DateField(widget=forms.TextInput(attrs={
        'class': 'datepicker'
    }))
    zip_code = USZipCodeField()
    state_province = USStateField(widget=forms.Select(choices=PROFILE_STATE_CHOICES))
    SSN = USSocialSecurityNumberField()
    phone = PhoneNumberField()
    fax = PhoneNumberField()

    class Meta:
        model = Profile
        fields = ('username', 'passport', 'sex', 'interest', 'marital', 'kids', 'next_of_kin', 'height', 'DOB', 'phone', 'fax', 'address', 'city', 'zip_code', 'state_province', 'SSN', 'country')
        widgets = {'country': CountrySelectWidget()}

class LoginForm(forms.Form):
    email    = forms.EmailField(label='Email')
    password = forms.CharField(widget=forms.PasswordInput)

    def __init__(self, request, *args, **kwargs):
        self.request = request
        super(LoginForm, self).__init__(*args, **kwargs)

    def clean(self):
        request = self.request
        data = self.cleaned_data
        email  = data.get("email")
        password  = data.get("password")
        qs = User.objects.filter(email=email)
        if qs.exists():
            # user email is registered, check active/
            not_active = qs.filter(is_active=False)
            if not_active.exists():
                ## not active, check email activation
                link = reverse("account:resend-activation")
                reconfirm_msg = """Go to <a href='{resend_link}'>
                resend confirmation email</a>.
                """.format(resend_link = link)
                confirm_email = EmailActivation.objects.filter(email=email)
                is_confirmable = confirm_email.confirmable().exists()
                if is_confirmable:
                    msg1 = "Please check your email to confirm your account or " + reconfirm_msg.lower()
                    raise forms.ValidationError(mark_safe(msg1))
                email_confirm_exists = EmailActivation.objects.email_exists(email).exists()
                if email_confirm_exists:
                    msg2 = "Email not confirmed. " + reconfirm_msg
                    raise forms.ValidationError(mark_safe(msg2))
                if not is_confirmable and not email_confirm_exists:
                    raise forms.ValidationError("This user is inactive.")
        user = authenticate(request, username=email, password=password)
        if user is None:
            raise forms.ValidationError("Invalid credentials")
        login(request, user)
        self.user = user
        return data

    # def form_valid(self, form):
    #     request = self.request
    #     next_ = request.GET.get('next')
    #     next_post = request.POST.get('next')
    #     redirect_path = next_ or next_post or None
    #     email  = form.cleaned_data.get("email")
    #     password  = form.cleaned_data.get("password")
        
    #     print(user)
    #     if user is not None:
    #         if not user.is_active:
    #             print('inactive user..')
    #             messages.success(request, "This user is inactive")
    #             return super(LoginView, self).form_invalid(form)
    #         login(request, user)
    #         user_logged_in.send(user.__class__, instance=user, request=request)
    #         try:
    #             del request.session['guest_email_id']
    #         except:
    #             pass
    #         if is_safe_url(redirect_path, request.get_host()):
    #             return redirect(redirect_path)
    #         else:
    #             return redirect("/")
    #     return super(LoginView, self).form_invalid(form)

accounts/views.py
from django.shortcuts import render
from django.contrib.auth import authenticate, login, get_user_model
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib import messages
from django.urls import reverse, reverse_lazy
from django.utils.decorators import method_decorator
from django.views.generic import CreateView, FormView, DetailView, View, UpdateView
from django.views.generic.edit import FormMixin
from django.http import HttpResponseRedirect
from django.shortcuts import render, redirect
from django.utils.http import is_safe_url
from django.utils.safestring import mark_safe
from django.db import transaction

from dating.mixins import NextUrlMixin, RequestFormAttachMixin
from .forms import LoginForm, UserRegisterForm, ReactivateEmailForm, UserDetailChangeForm, ProfileEditForm#, StaffDetailChangeForm, StaffRegisterForm
from .models import EmailActivation, User, Profile
from .signals import user_logged_in 


# Create your views here.
class AccountHomeView(LoginRequiredMixin, DetailView):
    template_name = 'accounts/home.html'
    def get_object(self):
        return self.request.user

class AccountEmailActivateView(FormMixin, View):
    success_url = '/login/'
    form_class = ReactivateEmailForm
    key = None
    def get(self, request, key=None, *args, **kwargs):
        self.key = key
        if key is not None:
            qs = EmailActivation.objects.filter(key__iexact=key)
            confirm_qs = qs.confirmable()
            if confirm_qs.count() == 1:
                obj = confirm_qs.first()
                obj.activate()
                messages.success(request, "Your email has been confirmed. Please login.")
                return redirect("login")
            else:
                activated_qs = qs.filter(activated=True)
                if activated_qs.exists():
                    reset_link = reverse("password_reset")
                    msg = """Your email has already been confirmed
                    Do you need to <a href="{link}">reset your password</a>?
                    """.format(link=reset_link)
                    messages.success(request, mark_safe(msg))
                    return redirect("login") 
        context = {'form': self.get_form(),'key': key}
        return render(request, 'registration/activation-error.html', context)

    def post(self, request, *args, **kwargs):
        # create form to receive an email
        form = self.get_form()
        if form.is_valid():
            return self.form_valid(form)
        else:
            return self.form_invalid(form)

    def form_valid(self, form):
        msg = """Activation link sent, please check your email."""
        request = self.request
        messages.success(request, msg)
        email = form.cleaned_data.get("email")
        obj = EmailActivation.objects.email_exists(email).first()
        user = obj.user 
        new_activation = EmailActivation.objects.create(user=user, email=email)
        new_activation.send_activation()
        return super(AccountEmailActivateView, self).form_valid(form)

    def form_invalid(self, form):
        context = {'form': form, "key": self.key }
        return render(self.request, 'registration/activation-error.html', context)

class LoginView(NextUrlMixin, RequestFormAttachMixin, FormView):
    form_class = LoginForm
    success_url = '/account'
    template_name = 'accounts/login.html'
    default_next = '/account'

    def form_valid(self, form):
        next_path = self.get_next_url()
        return redirect(next_path)

class RegisterView(CreateView):
    form_class = UserRegisterForm
    template_name = 'accounts/register.html'
    success_url = '/login/'



# Profile view update view for adding informations
@login_required
@transaction.atomic
def UserDetailUpdateView(request):
    if request.method == 'POST':
        user_form = UserDetailChangeForm(request.POST, instance=request.user)
        profile_form = ProfileEditForm(request.POST or None, instance=request.user.profile)
        if user_form.is_valid() and profile_form.is_valid():
            user_form.save()
            profile_form.save()
            messages.success(request, ('Your profile was successfully updated'))
            return redirect('account:home')
        else:
            messages.error(request, ('Please correct the error below.'))
    else:
        user_form = UserDetailChangeForm(instance=request.user)
        profile_form = ProfileEditForm(instance=request.user.profile)
    context = {
        'user_form': user_form,
        'profile_form': profile_form,
    }
    return render(request, 'accounts/detail-update.html', context)

accounts/templates/accounts/detail-update.html
{% extends "base.html" %}

{% block title %}
  EDIT PROFILE
{% endblock title %}


{% block navbar %}
{% include "snippets/nav.html" %}
{% endblock navbar %}


{% block content %}
<div class="title">
  {% if title %}
  <h3 class="center-align grey-text">{{ title }}!</h3>
  {% endif %}
</div>
  <div class="row">
    <div class="col s12 l6 offset-l3">
      <div class="card grey lighten-3">
        <div class="card-content">
          <h4 class="card-title center-align">Update Your Informations</h4>
          <form method="POST" action='{% if action_url %}{{ action_url }}{% endif %}'>
            {% csrf_token %}
            {% if user_form %}
            {{ user_form.non_field_errors }}
            {% for hidden_field in user_form.hidden_fields %}
                {{ hidden_field.errors }}
                {{ hidden_field }}
            {% endfor %}
            {% else %}
            {{ profile_form.non_field_errors }}
            {% for hidden_field in profile_form.hidden_fields %}
                {{ hidden_field.errors }}
                {{ hidden_field }}
            {% endfor %}
            {% endif %}
            {% if next_url %}
            <input type='hidden' name='next' value='{{ next_url }}' />
            {% endif %}
            <div class="row">
                <div class="input-field col s12">
                  <i class="material-icons prefix">email</i>
                  {{user_form.first_name}}
                  {{user_form.first_name.label_tag}}
                  <span class="helper-text" data-error="{{user_form.first_name.errors}}" data-success="right">{{user_form.first_name.help_text}}</span>
                </div>
            </div>
            <div class="row">
                <div class="input-field col s12">
                    <i class="material-icons prefix">email</i>
                    {{user_form.middle_name}}
                    {{user_form.middle_name.label_tag}}
                    <span class="helper-text" data-error="{{user_form.middle_name.errors}}" data-success="right">{{user_form.middle_name.help_text}}</span>
                </div>
            </div>
            <div class="row">
                <div class="input-field col s12">
                    <i class="material-icons prefix">email</i>
                    {{user_form.surname}}
                    {{user_form.surname.label_tag}}
                    <span class="helper-text" data-error="{{user_form.surname.errors}}" data-success="right">{{user_form.surname.help_text}}</span>
                </div>
            </div>
            <div class="row">
              <div class="input-field col s12">
                  <i class="material-icons prefix">email</i>
                  {{profile_form.username}}
                  {{profile_form.username.label_tag}}
                  <span class="helper-text" data-error="{{profile_form.username.errors}}" data-success="right">{{profile_form.username.help_text}}</span>
              </div>
          </div>
            <div class="row">
                <div class="file-field input-field col s12">
                  <div class="btn black white-text center-align">
                      <i class="material-icons">add_a_photo</i>
                      {{profile_form.passport}}
                  </div>
                  <div class="file-path-wrapper">
                    <input class="file-path validate black-text" type="text" placeholder="">
                  </div>
                  <span class="helper-text" data-error="{{profile_form.passport.errors}}" data-success="right">{{profile_form.passport.help_text}}</span>
                </div>
            </div>
            <div class="row">
                <div class="input-field col s12">
                    {{profile_form.sex}}
                    {{profile_form.sex.label_tag}}
                    <span class="helper-text" data-error="{{profile_form.sex.errors}}" data-success="right">{{profile_form.sex.help_text}}</span>
                </div>
            </div>
            <div class="row">
              <div class="input-field col s12">
                  {{profile_form.interest}}
                  {{profile_form.interest.label_tag}}
                  <span class="helper-text" data-error="{{profile_form.interest.errors}}" data-success="right">{{profile_form.interest.help_text}}</span>
              </div>
            </div>
            <div class="row">
                <div class="input-field col s12">
                    {{profile_form.marital}}
                    {{profile_form.marital.label_tag}}
                    <span class="helper-text" data-error="{{profile_form.marital.errors}}" data-success="right">{{profile_form.marital.help_text}}</span>
                </div>
            </div>
            <div class="row">
              <div class="input-field col s12">
                  {{profile_form.kids}}
                  {{profile_form.kids.label_tag}}
                  <span class="helper-text" data-error="{{profile_form.kids.errors}}" data-success="right">{{profile_form.kids.help_text}}</span>
              </div>
            </div>
            <div class="row">
                <div class="input-field col s12">
                  {{ profile_form.next_of_kin }}
                  {{ profile_form.next_of_kin.label_tag}}
                  <span class="helper-text" data-error="{{profile_form.next_of_kin.errors}}" data-success="right">{{profile_form.next_of_kin.help_text}}</span>
                </div>
            </div>
            <div class="row">
              <div class="input-field col s12">
                  {{profile_form.height}}
                  {{profile_form.height.label_tag}}
                  <span class="helper-text" data-error="{{profile_form.height.errors}}" data-success="right">{{profile_form.height.help_text}}</span>
              </div>
            </div>
            <div class="row">
                <div class="input-field col s12">
                  <input type="text" id="id_DOB" name="DOB" class="datepicker" required>
                  {{ profile_form.DOB.label_tag}}
                  <span class="helper-text" data-error="{{profile_form.DOB.errors}}" data-success="right">{{profile_form.DOB.help_text}}</span>
                </div>
              </div>
            <div class="row">
                <div class="input-field col s12">
                  {{profile_form.phone}}
                  {{profile_form.phone.label_tag}}
                  <span class="helper-text" data-error="{{profile_form.phone.errors}}" data-success="right">{{profile_form.phone.help_text}}</span>
                </div>
            </div>
            <div class="row">
                <div class="input-field col s12">
                  {{profile_form.fax}}
                  {{profile_form.fax.label_tag}}
                  <span class="helper-text" data-error="{{profile_form.fax.errors}}" data-success="right">{{profile_form.fax.help_text}}</span>
                </div>
            </div>
            <div class="row">
                <div class="input-field col s12">
                  {{profile_form.address}}
                  {{profile_form.address.label_tag}}
                  <span class="helper-text" data-error="{{profile_form.address.errors}}" data-success="right">{{profile_form.address.help_text}}</span>
                </div>
            </div>
            <div class="row">
              <div class="input-field col s12">
                {{profile_form.city}}
                {{profile_form.city.label_tag}}
                <span class="helper-text" data-error="{{profile_form.city.errors}}" data-success="right">{{profile_form.city.help_text}}</span>
              </div>
          </div>
            <div class="row">
                <div class="input-field col s12">
                  {{profile_form.zip_code}}
                  {{profile_form.zip_code.label_tag}}
                  <span class="helper-text" data-error="{{profile_form.zip_code.errors}}" data-success="right">{{profile_form.zip_code.help_text}}</span>
                </div>
            </div>
            <div class="row">
                <div class="input-field col s12">
                    {{profile_form.state_province}}
                    {{profile_form.state_province.label_tag}}
                  <span class="helper-text" data-error="{{profile_form.state_province.errors}}" data-success="right">{{profile_form.state_province.help_text}}</span>
                </div>
            </div>
            <div class="row">
                <div class="input-field col s12">
                  {{profile_form.SSN}}
                  {{profile_form.SSN.label_tag}}
                  <span class="helper-text" data-error="{{profile_form.SSN.errors}}" data-success="right">{{profile_form.SSN.help_text}}</span>
                </div>
            </div>
            <div class="row">
                <div class="input-field col s12">
                  {{profile_form.country}}
                  {{profile_form.country.label_tag}}
                  <span class="helper-text" data-error="{{profile_form.country.errors}}" data-success="right">{{profile_form.country.help_text}}</span>
                </div>
            </div>
            <div class="row">
              <div class="input-field col s12">
                <i class="material-icons prefix">email</i>
                <input type="email" id="email" class="validatec disabled"  value='{{ request.user.email }}' disabled="disabled"/>
                <span class='help-text'>Cannot change email</span><br/>
                <label for="email">Email:</label>
              </div>
            </div>
            <div class="row center-align">
              <button class="btn waves-effect waves-light" type="submit" name="action">Save
                <i class="material-icons right">send</i>
              </button>
            </div>
          </form>
          <p class="center-align"><a href="{% url 'password_change' %}"><em>Change Password</em></a></p>
        </div>
      </div>
    </div>
  </div>

{% endblock %}

accounts/templates/accounts/home.html
{% extends "base.html" %}

{% block title %}
  PROFILE
{% endblock title %}

{% block navbar %}
{% include "snippets/nav.html" %}
{% endblock navbar %}

{% block content %}
<div class='row'>
<div class='col-12 container'>
<h3 class="center-align">Hello {{ user.first_name}}</h3>
<p class="center-align">Right here you can <em>Review</em>, <em>Update</em> and even <em>Change</em> your user information and passwords.</p>
</div>


<div class='col s12 m10 offset-m1'>
    <div class="card grey lighten-2">
      <div class="card-content">
        <h4 class="card-title center-align">Account Details</h4> 
        <div class="divider"></div>
        <hr>
        <div class="row center-align">
          <div class="col s12 l6">
           <h6>{{ user.short_name }}</h6>
            <small><em><b>Short Name</b></em></small><br>
          <br>
          </div>
          
          <div class="col s12 l6">
             <h6>{{ user.middle_name }}</h6>
              <small><em><b>Middle Name</b></em></small><br>
            <br>
            </div>
            
            <div class="col s12 l6">
               <h6>{{ user.email }}</h6>
                <small><em><b>Email</b></em></small>
              </div>

        </div>
        <hr>
        <br>
        <div class='row'>
          <div class="col s6 l6">
            <a class='center-align' href='{% url "account:user-update" %}'>Update Profile</a>
          </div>
          <div class="col s6 l6 right-align">
            <a class='center-align' href='{% url "password_change" %}'>Change Password</a>          </div>
          </div>
      </div>
    </div>
</div>

</div>


{% endblock %}

accounts/templates/accounts/login.html
{% extends "base.html" %}
{% block title %}
  LOGIN
{% endblock title %}

{% block content %}
<div class="title">
  <h3 class="center-align grey-text"><a href="{% url 'home' %}">React Capitals</a></h3>
</div>
<div class="row">
  <div class="col s12 l6 offset-l3">
    <div class="card grey lighten-3">
      <div class="card-content">
        <h4 class="card-title center-align">Login</h4>
        <form method="POST">
          {% csrf_token %}
         <div class="center-align">
            {{ form.non_field_errors }}
          {% for hidden_field in form.hidden_fields %}
              {{ hidden_field.errors }}
              {{ hidden_field }}
          {% endfor %}
         </div>
          <div class="row">
            <div class="input-field col s12">
              <i class="material-icons prefix">email</i>
              {{form.email}}
              {{form.email.label_tag}}
              <span class="helper-text" data-error="{{form.email.errors}}" data-success="right">{{form.email.help_text}}</span>
            </div>
          </div>
          <div class="row">
            <div class="input-field col s12">
              <i class="material-icons prefix">vpn_key</i>
              {{form.password}}
              {{form.password.label_tag}}
              <span class="helper-text" data-error="{{form.password.errors}}" data-success="right">{{form.password.help_text}}</span>
            </div>
          </div>
          <div class="row center-align">
            <button class="btn waves-effect waves-light" type="submit" name="action">Submit
              <i class="material-icons right">send</i>
            </button>
          </div>
        </form>
        <p class="center-align"><a href="{% url 'register' %}"><em>Don't have an account?</em></a></p>
      </div>
    </div>
  </div>
</div>
{% endblock %}