dating/urls.py
from django.conf import settings
from django.conf.urls.static import static

from django.contrib import admin
from django.urls import path, re_path, include

#ACCOUNT VIEW IMPORTS
from django.contrib.auth.views import LogoutView
from django.views.generic import TemplateView, RedirectView
from accounts.views import LoginView, RegisterView#, StaffRegisterView

#Project Main Views (home, about, contact)
from .views import index

# from questions.views import single, home
# from newsletter.views import contact
# from likes.views import like_user
# from profiles.views import profile_edit, profile_user, profile_view, job_add, jobs_edit

urlpatterns = [
    path('admin/', admin.site.urls),

    # Home, Contact & About urls
    path('', index, name='home'),

    #ACCOUNT LINKS AND PASSWORD(LOGIN & LOGOUT)
    path('accounts/', RedirectView.as_view(url='/account')),
    path('account/', include("accounts.urls", namespace='account')),
    path('accounts/', include("accounts.passwords.urls")),
    path('login/', LoginView.as_view(), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('register/', RegisterView.as_view(), name='register'),

    #APPS URLS
    # path('', 'dashboard.views.home', name='home'),
    # re_path(r'^question/(?P<id>\d+)/$', single, name='question_single'),
    # path('question/', home, name='question_home'),
    # path('contact/', contact, name='contact'),
    # path('matches/', include('matches.urls', namespace='matches')),
    # re_path(r'^like/(?P<id>\d+)/$', like_user, name='like_user'),
    # path('profile/edit/', profile_edit, name='profile_edit'),
    # re_path(r'^profile/(?P<username>[\w.@+-]+)/$', profile_view, name='profile'),
    # path('profile/jobs/add/', job_add, name='job_add'),
    # path('profile/jobs/edit/', jobs_edit, name='jobs_edit'),
    # path('profile/', profile_user, name='profile_user'),
]

if settings.DEBUG:
    urlpatterns = urlpatterns + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns = urlpatterns + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/snippets/css.html
{% load static %}
<!--Import Google Icon Font-->
<link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
<link rel="stylesheet" href="{% static 'css/materialize.min.css' %}" media="screen,projection">

<link rel="stylesheet" href="{% static 'css/main.css' %}">

templates/snippets/footer.html
<footer class="page-footer blue-grey lighten-3 white-text">
    <div class="container-fluid ">
        <div class="row">
            <div class="col s12 center-align l4">
                <div class="btcwdgt-news" bw-entries="5" bw-cur="eur"></div>
            </div>
            <div class="col l4 blue-grey-text text-darken-4 s12 center-align ">
                <h5>REACTCAPITALS</h5>
                <p>Loan, Digital Asset Clearing House and Brokerage</p>
            </div>
            <div class="col s12 center-align l4">
                <div class="btcwdgt-news"  bw-entries="5" bw-cur="usd"></div>
            </div>
        </div>
    </div>
    <div class="footer-copyright blue-grey darken-4">
        <div class="container center-align">
        © 2019 Copyright React Capitals
        </div>
    </div>
</footer>

templates/snippets/js.html
{% load static %}
<!--Import jQuery Library-->
<script type="text/javascript" src="https://code.jquery.com/jquery-3.2.1.min.js"></script>

<script src="{% static 'js/materialize.min.js' %}"></script>
<script src="{% static 'js/main.js' %}"></script>
<script src="{% static 'js/init.js' %}"></script>

templates/snippets/nav.html
{% url 'login' as login_url %}
{% url 'logout' as logout_url %}
{% url 'register' as register_url %}

{% url 'home' as index_url %}
{% url 'contact' as contact_url %}
{% url 'email-success' as success_url %}
{% url 'account:home' as account_url %}
{% url 'password_change' as password_change_url %}


<div class="navbar-fixed">
    <nav class="blue-grey darken-4" role="navigation">
        <div class="nav-wrapper container-fluid">
            <a href="#" data-target="nav-mobile" class="left show-on-large sidenav-icon sidenav-trigger"><i class="material-icons white-text">menu</i></a>
            <a id="logo-container" href="{% url 'home' %}" class="brand-logo center">Dating</a>
            <ul class="right nav-link white-text">
                <li><a href="#!" class="dropdown-trigger" data-target="settings"><i class="material-icons right white-text">account_circle</i><em class="hide-on-small-only">{{user.short_name}}</em></a></li>        
            </ul>
        </div>
    </nav>    
</div>
<ul id="nav-mobile" class="blue-grey darken-2 sidenav">
    <form style="position:relative;margin-top:-1em;margin-bottom:2em;">
        <div class="input-field">
            <input id="search" type="search" required>
            <label style="padding-top:6px;" class="label-icon" for="search"><i class="material-icons">search</i></label>
            <i style="padding-top:6px;" class="material-icons">close</i>
        </div>
    </form>
    <li class="{% if request.path == index_url %}active{% endif %}"><a href="{{index_url}}" class="white-text">HOME</a></li>
    <li class="{% if request.path == contact_url %}active{% elif request.path == success_url %}active{% endif %}"><a href="{{contact_url}}" class="white-text">CONTACT</a></li>
    
</ul>
<ul id="settings" class="dropdown-content">
    {% if not user.is_authenticated %}
    <li class="{% if request.path == login_url %}active{% endif %} right-align"><a href="{{login_url}}" class=" blue-grey-text">login</a></li>
    <li class="{% if request.path == register_url %}active{% endif %} right-align"><a href="{{register_url}}" class="blue-grey-text">register</a></li>
    {% else %}
    <li class="{% if request.path == account_url %}active{% endif %} right-align"><a href="{{account_url}}" class=" blue-grey-text">Profile</a></li>
    <li class="{% if request.path == password_change_url %}active{% endif %} right-align"><a href="{{password_change_url}}" class=" blue-grey-text">settings</a></li>
    <li class="divider"></li>
    <li class="{% if request.path == logout_url %}active{% endif %} right-align"><a href="{{logout_url}}" class="blue-grey-text">logout</a></li>
    {% endif %}
</ul>